[default_session]
command = "agreety --cmd /usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland"
user = "greeter"

[initial_session]
command = "/usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland"
user = "cyrus"

[terminal]
vt = 1
