services:
    search-engine:
        image: docker.io/searxng/searxng
        container_name: search-engine
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - configuration:/etc/searxng
            - data:/var/cache/searxng

volumes:
    configuration:
    data:
