name: Dispatch build event to cyrus01337/shell-devcontainer

on:
    push:
        branches: ["main"]
        paths:
            - ".config/**"
            - ".github/workflows/**"
            - "bin/**"
            - ".bashrc"
            - ".stow-local-ignore"
    workflow_dispatch:

jobs:
    trigger-event:
        name: Dispatch build event
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
                  submodules: true

            - name: Update submodules to latest
              run: |
                git submodule update --init --recursive
                git submodule update --remote --recursive
                git add .
                git commit -m "Update to latest"

                if [[ $? == 0 ]]; then
                    git push
                fi

                exit 0

            - name: Parse short commit hash
              id: commit-hash
              run: |
                SHORT_COMMIT_HASH="$(git rev-parse --short HEAD)"

                echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> "$GITHUB_ENV"

            - name: Dispatch
              env:
                WORKFLOW_DISPATCH_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
              run: |
                status_code=$(
                    curl -L \
                        -X POST \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer $WORKFLOW_DISPATCH_TOKEN" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/cyrus01337/shell-devcontainer/dispatches \
                        -d '{"event_type":"Handle build request (dotfiles-but-better@${{ env.SHORT_COMMIT_HASH }})"}' \
                        | jq ".status" \
                        | sed -E 's/"(.+)"/\1/'
                )

                if [[ $status_code ]]; then
                    echo "Request status code: $status_code..."

                   exit 1
                fi
